name=Poom
version=1.1.0
author=Poom
maintainer=Michelle Mendez <jupiter@stellar-iot.com>
sentence=Arduino library for developing applications on the Poom device.
paragraph=Provides access to Poom hardware features for building applications, games, experiments, and hardware projects.
category=Device Control
url=https://github.com/The-POOM/poom-arduino
architectures=esp32
includes=Poom.h
depends=Adafruit SH110X, Adafruit NeoPixel
